export const componentNavLinks: Array<{ href: string; label: string }> = [
  { href: "/floatingdock", label: "Floating Dock" },
  { href: "/datepicker", label: "Date Picker" },
  { href: "/svgtoc", label: "SVG Curved TOC" },
  { href: "/mathcurveloaders", label: "Math Curve Loaders" },
  { href: "/chainselector", label: "Chain Selector" },
  { href: "/nfttable", label: "NFT Collections Table" },
  { href: "/avatarcreator", label: "Avatar Creator" },
  { href: "/pnlcalendar", label: "PnL Calendar" },
  { href: "/peektext", label: "Peektext" },
  { href: "/canvasgallery", label: "Canvas Gallery" },
  { href: "/floating-toolbar-tooltip", label: "Floating Toolbar Tooltip" },
  { href: "/slide-to-convert-button", label: "Slide To Convert Button" },
  { href: "/buttons", label: "Button Components" },
  { href: "/track-status-button", label: "Track Status Button" },
  { href: "/fix-action-buttons", label: "Fix Action Buttons" },
  { href: "/performancebutton", label: "Performance Button" },
  { href: "/figma-properties-button", label: "Figma Properties Button" },
  { href: "/fun-loading-button", label: "FUN Loading Button" },
  { href: "/light-gradient-button", label: "Light Gradient Button" },
  { href: "/orange-add-view-button", label: "Orange Add View Button" },
  { href: "/buy-now-glow-button", label: "Buy Now Glow Button" },
  { href: "/glossy-icon-buttons", label: "Glossy Icon Buttons" },
  { href: "/lime-alert-rule-button", label: "Lime Alert Rule Button" },
  { href: "/preview-deploy-buttons", label: "Preview Deploy Buttons" },
  { href: "/earn-button", label: "Earn Button" },
];
