export const componentNavLinks: Array<{ href: string; label: string }> = [
  { href: "/floatingdock", label: "Floating Dock" },
  { href: "/agentstatus", label: "Agent Status Panels" },
  { href: "/tabpatterns", label: "Tab Patterns" },
  { href: "/agenttoasts", label: "Agent System Toasts" },
  { href: "/tokenselector", label: "Token Selector Modal" },
  { href: "/timeframe", label: "Timeframe Selector" },
  { href: "/boneyard", label: "Boneyard Skeleton" },
  { href: "/datepicker", label: "Date Picker" },
  { href: "/svgtoc", label: "SVG Curved TOC" },
  { href: "/friportfolio", label: "FRI Portfolio Dashboard" },
  { href: "/mathcurveloaders", label: "Math Curve Loaders" },
  { href: "/navbar", label: "Navbar" },
  { href: "/chainselector", label: "Chain Selector" },
  { href: "/deficard", label: "DeFi Card" },
  { href: "/nfttable", label: "NFT Collections Table" },
  { href: "/gascard", label: "Gas Fee Mode Selector" },
  { href: "/marketstatcard", label: "Market Stats Card" },
  { href: "/dominancebarcard", label: "Dominance Bar Card" },
  { href: "/transactions", label: "Transaction Toast" },
  { href: "/swap-flow", label: "Swap Flow" },
  { href: "/avatarcreator", label: "Avatar Creator" },
  { href: "/pnlcalendar", label: "PnL Calendar" },
  { href: "/peektext", label: "Peektext" },
  { href: "/folder", label: "Folder" },
  { href: "/canvasgallery", label: "Canvas Gallery" },
  { href: "/landthebooster", label: "Land the Booster" },
  { href: "/investmentgrowth", label: "Investment Growth Chart" },
  { href: "/performancebutton", label: "Performance Button" },
];
